// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: open-authentication-screen
// Dev server: http://127.0.0.1:5173/
import { test, expect } from '@playwright/test';

test('open-authentication-screen', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/');
  await expect(page.getByText("Anmeldung").first()).toBeVisible();
  await expect(page.getByText("Registrieren").first()).toBeVisible();
  await expect(page.getByText("Anmelden").first()).toBeVisible();
});
